from unittest import TestCase

from objectmodel.enums.State import State


class TestState(TestCase):
    def test_text(self):
        self.assertEquals("Alabama", State.ALABAMA.text)
        self.assertEquals("Alaska", State.ALASKA.text)
        self.assertEquals("Arizona", State.ARIZONA.text)
        self.assertEquals("Arkansas", State.ARKANSAS.text)
        self.assertEquals("California", State.CALIFORNIA.text)
        self.assertEquals("Colorado", State.COLORADO.text)
        self.assertEquals("Connecticut", State.CONNECTICUT.text)
        self.assertEquals("Delaware", State.DELAWARE.text)
        self.assertEquals("District of Columbia", State.DISTRICT_OF_COLUMBIA.text)
        self.assertEquals("Florida", State.FLORIDA.text)
        self.assertEquals("Georgia", State.GEORGIA.text)
        self.assertEquals("Hawaii", State.HAWAII.text)
        self.assertEquals("Idaho", State.IDAHO.text)
        self.assertEquals("Illinois", State.ILLINOIS.text)
        self.assertEquals("Indiana", State.INDIANA.text)
        self.assertEquals("Iowa", State.IOWA.text)
        self.assertEquals("Kansas", State.KANSAS.text)
        self.assertEquals("Kentucky", State.KENTUCKY.text, )
        self.assertEquals("Louisiana", State.LOUISIANA.text)
        self.assertEquals("Maine", State.MAINE.text)
        self.assertEquals("Maryland", State.MARYLAND.text)
        self.assertEquals("Massachusetts", State.MASSACHUSETTS.text)
        self.assertEquals("Michigan", State.MICHIGAN.text)
        self.assertEquals("Minnesota", State.MINNESOTA.text)
        self.assertEquals("Mississippi", State.MISSISSIPPI.text)
        self.assertEquals("Missouri", State.MISSOURI.text)
        self.assertEquals("Montana", State.MONTANA.text)
        self.assertEquals("Nebraska", State.NEBRASKA.text)
        self.assertEquals("Nevada", State.NEVADA.text)
        self.assertEquals("New Hampshire", State.NEW_HAMPSHIRE.text)
        self.assertEquals("New Jersey", State.NEW_JERSEY.text)
        self.assertEquals("New Mexico", State.NEW_MEXICO.text)
        self.assertEquals("New York", State.NEW_YORK.text)
        self.assertEquals("North Carolina", State.NORTH_CAROLINA.text)
        self.assertEquals("North Dakota", State.NORTH_DAKOTA.text)
        self.assertEquals("Ohio", State.OHIO.text)
        self.assertEquals("Oklahoma", State.OKLAHOMA.text)
        self.assertEquals("Oregon", State.OREGON.text)
        self.assertEquals("Pennsylvania", State.PENNSYLVANIA.text)
        self.assertEquals("Rhode Island", State.RHODE_ISLAND.text)
        self.assertEquals("South Carolina", State.SOUTH_CAROLINA.text)
        self.assertEquals("South Dakota", State.SOUTH_DAKOTA.text)
        self.assertEquals("Tennessee", State.TENNESSEE.text)
        self.assertEquals("Texas", State.TEXAS.text)
        self.assertEquals("Utah", State.UTAH.text)
        self.assertEquals("Vermont", State.VERMONT.text)
        self.assertEquals("Virginia", State.VIRGINIA.text)
        self.assertEquals("Washington", State.WASHINGTON.text)
        self.assertEquals("West Virginia", State.WEST_VIRGINIA.text)
        self.assertEquals("Wisconsin", State.WISCONSIN.text)
        self.assertEquals("Wyoming", State.WYOMING.text)

    def test_abbreviation(self):
        self.assertEquals("AL", State.ALABAMA.abbreviation)
        self.assertEquals("AK", State.ALASKA.abbreviation)
        self.assertEquals("AZ", State.ARIZONA.abbreviation)
        self.assertEquals("AR", State.ARKANSAS.abbreviation)
        self.assertEquals("CA", State.CALIFORNIA.abbreviation)
        self.assertEquals("CO", State.COLORADO.abbreviation)
        self.assertEquals("CT", State.CONNECTICUT.abbreviation)
        self.assertEquals("DE", State.DELAWARE.abbreviation)
        self.assertEquals("DC", State.DISTRICT_OF_COLUMBIA.abbreviation)
        self.assertEquals("FL", State.FLORIDA.abbreviation)
        self.assertEquals("GA", State.GEORGIA.abbreviation)
        self.assertEquals("HI", State.HAWAII.abbreviation)
        self.assertEquals("ID", State.IDAHO.abbreviation)
        self.assertEquals("IL", State.ILLINOIS.abbreviation)
        self.assertEquals("IN", State.INDIANA.abbreviation)
        self.assertEquals("IA", State.IOWA.abbreviation)
        self.assertEquals("KS", State.KANSAS.abbreviation)
        self.assertEquals("KY", State.KENTUCKY.abbreviation)
        self.assertEquals("LA", State.LOUISIANA.abbreviation)
        self.assertEquals("ME", State.MAINE.abbreviation)
        self.assertEquals("MD", State.MARYLAND.abbreviation)
        self.assertEquals("MA", State.MASSACHUSETTS.abbreviation)
        self.assertEquals("MI", State.MICHIGAN.abbreviation)
        self.assertEquals("MN", State.MINNESOTA.abbreviation)
        self.assertEquals("MS", State.MISSISSIPPI.abbreviation)
        self.assertEquals("MO", State.MISSOURI.abbreviation)
        self.assertEquals("MT", State.MONTANA.abbreviation)
        self.assertEquals("NE", State.NEBRASKA.abbreviation)
        self.assertEquals("NV", State.NEVADA.abbreviation)
        self.assertEquals("NH", State.NEW_HAMPSHIRE.abbreviation)
        self.assertEquals("NJ", State.NEW_JERSEY.abbreviation)
        self.assertEquals("NM", State.NEW_MEXICO.abbreviation)
        self.assertEquals("NY", State.NEW_YORK.abbreviation)
        self.assertEquals("NC", State.NORTH_CAROLINA.abbreviation)
        self.assertEquals("ND", State.NORTH_DAKOTA.abbreviation)
        self.assertEquals("OH", State.OHIO.abbreviation)
        self.assertEquals("OK", State.OKLAHOMA.abbreviation)
        self.assertEquals("OR", State.OREGON.abbreviation)
        self.assertEquals("PA", State.PENNSYLVANIA.abbreviation)
        self.assertEquals("RI", State.RHODE_ISLAND.abbreviation)
        self.assertEquals("SC", State.SOUTH_CAROLINA.abbreviation)
        self.assertEquals("SD", State.SOUTH_DAKOTA.abbreviation)
        self.assertEquals("TN", State.TENNESSEE.abbreviation)
        self.assertEquals("TX", State.TEXAS.abbreviation)
        self.assertEquals("UT", State.UTAH.abbreviation)
        self.assertEquals("VT", State.VERMONT.abbreviation)
        self.assertEquals("VA", State.VIRGINIA.abbreviation)
        self.assertEquals("WA", State.WASHINGTON.abbreviation)
        self.assertEquals("WV", State.WEST_VIRGINIA.abbreviation)
        self.assertEquals("WI", State.WISCONSIN.abbreviation)
        self.assertEquals("WY", State.WYOMING.abbreviation)

    def test_get(self):
        self.assertEquals(State.get("AL"), State.ALABAMA)
        self.assertEquals(State.get("AK"), State.ALASKA)
        self.assertEquals(State.get("AZ"), State.ARIZONA)
        self.assertEquals(State.get("AR"), State.ARKANSAS)
        self.assertEquals(State.get("CA"), State.CALIFORNIA)
        self.assertEquals(State.get("CO"), State.COLORADO)
        self.assertEquals(State.get("CT"), State.CONNECTICUT)
        self.assertEquals(State.get("DE"), State.DELAWARE)
        self.assertEquals(State.get("DC"), State.DISTRICT_OF_COLUMBIA)
        self.assertEquals(State.get("FL"), State.FLORIDA)
        self.assertEquals(State.get("GA"), State.GEORGIA)
        self.assertEquals(State.get("HI"), State.HAWAII)
        self.assertEquals(State.get("ID"), State.IDAHO)
        self.assertEquals(State.get("IL"), State.ILLINOIS)
        self.assertEquals(State.get("IN"), State.INDIANA)
        self.assertEquals(State.get("IA"), State.IOWA)
        self.assertEquals(State.get("KS"), State.KANSAS)
        self.assertEquals(State.get("KY"), State.KENTUCKY)
        self.assertEquals(State.get("LA"), State.LOUISIANA)
        self.assertEquals(State.get("ME"), State.MAINE)
        self.assertEquals(State.get("MD"), State.MARYLAND)
        self.assertEquals(State.get("MA"), State.MASSACHUSETTS)
        self.assertEquals(State.get("MI"), State.MICHIGAN)
        self.assertEquals(State.get("MN"), State.MINNESOTA)
        self.assertEquals(State.get("MS"), State.MISSISSIPPI)
        self.assertEquals(State.get("MO"), State.MISSOURI)
        self.assertEquals(State.get("MT"), State.MONTANA)
        self.assertEquals(State.get("NE"), State.NEBRASKA)
        self.assertEquals(State.get("NV"), State.NEVADA)
        self.assertEquals(State.get("NH"), State.NEW_HAMPSHIRE)
        self.assertEquals(State.get("NJ"), State.NEW_JERSEY)
        self.assertEquals(State.get("NM"), State.NEW_MEXICO)
        self.assertEquals(State.get("NY"), State.NEW_YORK)
        self.assertEquals(State.get("NC"), State.NORTH_CAROLINA)
        self.assertEquals(State.get("ND"), State.NORTH_DAKOTA)
        self.assertEquals(State.get("OH"), State.OHIO)
        self.assertEquals(State.get("OK"), State.OKLAHOMA)
        self.assertEquals(State.get("OR"), State.OREGON)
        self.assertEquals(State.get("PA"), State.PENNSYLVANIA)
        self.assertEquals(State.get("RI"), State.RHODE_ISLAND)
        self.assertEquals(State.get("SC"), State.SOUTH_CAROLINA)
        self.assertEquals(State.get("SD"), State.SOUTH_DAKOTA)
        self.assertEquals(State.get("TN"), State.TENNESSEE)
        self.assertEquals(State.get("TX"), State.TEXAS)
        self.assertEquals(State.get("UT"), State.UTAH)
        self.assertEquals(State.get("VT"), State.VERMONT)
        self.assertEquals(State.get("VA"), State.VIRGINIA)
        self.assertEquals(State.get("WA"), State.WASHINGTON)
        self.assertEquals(State.get("WV"), State.WEST_VIRGINIA)
        self.assertEquals(State.get("WI"), State.WISCONSIN)
        self.assertEquals(State.get("WY"), State.WYOMING)

        self.assertEquals(State.get("al"), State.ALABAMA)
        self.assertEquals(State.get("ak"), State.ALASKA)
        self.assertEquals(State.get("az"), State.ARIZONA)
        self.assertEquals(State.get("ar"), State.ARKANSAS)
        self.assertEquals(State.get("ca"), State.CALIFORNIA)
        self.assertEquals(State.get("co"), State.COLORADO)
        self.assertEquals(State.get("ct"), State.CONNECTICUT)
        self.assertEquals(State.get("de"), State.DELAWARE)
        self.assertEquals(State.get("dc"), State.DISTRICT_OF_COLUMBIA)
        self.assertEquals(State.get("fl"), State.FLORIDA)
        self.assertEquals(State.get("ga"), State.GEORGIA)
        self.assertEquals(State.get("hi"), State.HAWAII)
        self.assertEquals(State.get("id"), State.IDAHO)
        self.assertEquals(State.get("il"), State.ILLINOIS)
        self.assertEquals(State.get("in"), State.INDIANA)
        self.assertEquals(State.get("ia"), State.IOWA)
        self.assertEquals(State.get("ks"), State.KANSAS)
        self.assertEquals(State.get("ky"), State.KENTUCKY)
        self.assertEquals(State.get("la"), State.LOUISIANA)
        self.assertEquals(State.get("me"), State.MAINE)
        self.assertEquals(State.get("md"), State.MARYLAND)
        self.assertEquals(State.get("ma"), State.MASSACHUSETTS)
        self.assertEquals(State.get("mi"), State.MICHIGAN)
        self.assertEquals(State.get("mn"), State.MINNESOTA)
        self.assertEquals(State.get("ms"), State.MISSISSIPPI)
        self.assertEquals(State.get("mo"), State.MISSOURI)
        self.assertEquals(State.get("mt"), State.MONTANA)
        self.assertEquals(State.get("ne"), State.NEBRASKA)
        self.assertEquals(State.get("nv"), State.NEVADA)
        self.assertEquals(State.get("nh"), State.NEW_HAMPSHIRE)
        self.assertEquals(State.get("nj"), State.NEW_JERSEY)
        self.assertEquals(State.get("nm"), State.NEW_MEXICO)
        self.assertEquals(State.get("ny"), State.NEW_YORK)
        self.assertEquals(State.get("nc"), State.NORTH_CAROLINA)
        self.assertEquals(State.get("nd"), State.NORTH_DAKOTA)
        self.assertEquals(State.get("oh"), State.OHIO)
        self.assertEquals(State.get("ok"), State.OKLAHOMA)
        self.assertEquals(State.get("or"), State.OREGON)
        self.assertEquals(State.get("pa"), State.PENNSYLVANIA)
        self.assertEquals(State.get("ri"), State.RHODE_ISLAND)
        self.assertEquals(State.get("sc"), State.SOUTH_CAROLINA)
        self.assertEquals(State.get("sd"), State.SOUTH_DAKOTA)
        self.assertEquals(State.get("tn"), State.TENNESSEE)
        self.assertEquals(State.get("tx"), State.TEXAS)
        self.assertEquals(State.get("ut"), State.UTAH)
        self.assertEquals(State.get("vt"), State.VERMONT)
        self.assertEquals(State.get("va"), State.VIRGINIA)
        self.assertEquals(State.get("wa"), State.WASHINGTON)
        self.assertEquals(State.get("wv"), State.WEST_VIRGINIA)
        self.assertEquals(State.get("wi"), State.WISCONSIN)
        self.assertEquals(State.get("wy"), State.WYOMING)

        self.assertIsNone(State.get("ZZ"))
